# Generated by Django 4.2.30 on 2026-04-26 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("in_progress", "En progreso"),
                            ("in_bodywork", "En chapa"),
                            ("waiting_parts", "Esperando piezas"),
                            ("in_painting", "En pintura"),
                            ("quality_control", "Control de calidad"),
                            ("ready", "Listo para entrega"),
                            ("delivered", "Entregado"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "final_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("estimated_completion", models.DateField(blank=True, null=True)),
                ("actual_completion", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role__in": ["mechanic", "painter"]},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_work_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_work_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_orders",
                        to="customers.customer",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_orders",
                        to="customers.vehicle",
                    ),
                ),
            ],
            options={
                "db_table": "work_orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkOrderStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_status", models.CharField(max_length=20)),
                ("to_status", models.CharField(max_length=20)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="workorders.workorder",
                    ),
                ),
            ],
            options={
                "db_table": "work_order_status_history",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("bodywork", "Chapa"),
                            ("painting", "Pintura"),
                            ("mechanical", "Mecanica"),
                            ("electrical", "Electricidad"),
                            ("other", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "estimated_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "actual_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "labor_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "parts_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="workorders.workorder",
                    ),
                ),
            ],
            options={
                "db_table": "work_order_items",
            },
        ),
        migrations.AddIndex(
            model_name="workorder",
            index=models.Index(fields=["status"], name="work_orders_status_3f6c76_idx"),
        ),
        migrations.AddIndex(
            model_name="workorder",
            index=models.Index(
                fields=["assigned_to"], name="work_orders_assigne_88b76e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workorder",
            index=models.Index(
                fields=["created_at"], name="work_orders_created_5fb8d6_idx"
            ),
        ),
    ]
