# Generated by Django 4.2.30 on 2026-04-27 19:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0002_workordercomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('work_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='survey', to='workorders.workorder')),
            ],
            options={
                'db_table': 'work_order_surveys',
            },
        ),
    ]
