# Generated by Django 4.2.30 on 2026-04-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="work_orders/%Y/%m/")),
                (
                    "photo_type",
                    models.CharField(
                        choices=[
                            ("damage", "Danos iniciales"),
                            ("progress", "Progreso"),
                            ("final", "Resultado final"),
                            ("document", "Documento"),
                        ],
                        default="damage",
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                ("taken_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "photos",
                "ordering": ["-taken_at"],
            },
        ),
    ]
