# Generated by Django 4.2.30 on 2026-04-26 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("invoices", "0001_initial"),
        ("workorders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="work_order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoice",
                to="workorders.workorder",
            ),
        ),
    ]
